### ISSUE TITLE
Add spatial coordinate documentation into the docs folder

### ISSUE THREAD

**Issue by jminor** [AcademySoftwareFoundation/OpenTimelineIO#1090]
## Feature Request

Let's add the documentation for the spatial coordinates feature into the OTIO docs.

**Comment by jminor** [comment]
The docs are here https://github.com/PixarAnimationStudios/OpenTimelineIO/issues/1090
but there doesn't seem to be a link from the table of contents.

**Comment by JeanChristopheMorinPerso** [comment]
@jminor someone would need to add it in https://github.com/PixarAnimationStudios/OpenTimelineIO/blob/main/docs/index.rst#tutorials.

**Comment by jminor** [comment]
Addressed by https://github.com/AcademySoftwareFoundation/OpenTimelineIO/pull/1209
