### ISSUE TITLE
Read the Docs line length

### ISSUE THREAD

**Issue by ThomasWilshaw** [AcademySoftwareFoundation/OpenTimelineIO#1139]
Whilst looking through the docs  [here](https://opentimelineio.readthedocs.io/en/latest/tutorials/otio-serialized-schema.html?highlight=image%20sequence#imagesequencereference-1) I noticed some of the descriptive text in the documentation has a very long line length making viewing a bit of a pain. I have opened a PR to fix this issue and will have a look to see if it's the same any where else.

**Comment by meshula** [comment]
since you submitted a PR, I assume you didn't find any other unwrapped things?

**Comment by ThomasWilshaw** [comment]
There were a few other places but they were all single line commands rather than blocks of text and I assume should be left as a single line?
