### ISSUE TITLE
Gap python constructors have "effects" list mislabeled "effect"

### ISSUE THREAD

**Issue by reinecke** [AcademySoftwareFoundation/OpenTimelineIO#1188]
### Incorrect Functionality and General Questions

The python [gap constructors](https://github.com/PixarAnimationStudios/OpenTimelineIO/blob/990a54ccbe6488180a93753370fc87902b982962/src/py-opentimelineio/opentimelineio-bindings/otio_serializableObjects.cpp#L373-L394) accept a keyword argument `effect` which is a list of `Effect` instances:
```python
1. __init__(self: opentimelineio._otio.Gap, name: str = '', source_range: opentimelineio._opentime.TimeRange = otio.opentime.TimeRange(start_time=otio.opentime.RationalTime(value=0, rate=1), duration=otio.opentime.RationalTime(value=0, rate=1)), effect: object = None, markers: object = None, metadata: object = None) -> None

2. __init__(self: opentimelineio._otio.Gap, name: str = '', duration: opentimelineio._opentime.RationalTime = otio.opentime.RationalTime(value=0, rate=1), effect: object = None, markers: object = None, metadata: object = None) -> None
```

## To Reproduce

Using the python REPL, the following shows the issue:

```python
>>> otio.schema.Gap(effects=[])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. opentimelineio._otio.Gap(name: str = '', source_range: opentimelineio._opentime.TimeRange = otio.opentime.TimeRange(start_time=otio.opentime.RationalTime(value=0, rate=1), duration=otio.opentime.RationalTime(value=0, rate=1)), effect: object = None, markers: object = None, metadata: object = None)
    2. opentimelineio._otio.Gap(name: str = '', duration: opentimelineio._opentime.RationalTime = otio.opentime.RationalTime(value=0, rate=1), effect: object = None, markers: object = None, metadata: object = None)

Invoked with: kwargs: effects=[]
>>> otio.schema.Gap(effect=[])
otio.schema.Gap(name='', source_range=otio.opentime.TimeRange(start_time=otio.opentime.RationalTime(value=0, rate=1), duration=otio.opentime.RationalTime(value=0, rate=1)), effects=[], markers=[], metadata={})
```

## Expected Behavior

The library convention is to make the constructor arg match the property name (`effects` in this case).

## Additional Context

Is the `effects` list useful to specify in a Gap constructor? What is the semantic meaning of an effect on a Gap? Is it possible for an effect on a gap to try and convert it to something other than 100% transparent or somehow yielding audio?

**Comment by jminor** [comment]
We haven't specified how effects are meant to composite in OTIO, but in looking at use cases from AAF we often see text title effects on Gaps (Filler in AAF). Other times, we see video effects (blur, tint, etc.) on a Gap which then applies to the image composite below the Gap. For example, a long Gap covering a whole sequence on a top track could then apply an effect to the whole thing.
One might argue that this type of "filler" is more of a Clip with a transparent generator reference instead of a Gap, but today they are Gaps.

**Comment by reinecke** [comment]
Super useful context @jminor! It sounds like separate from this issue there are some design discussions to have about how to address those "effect on a gap" use cases - we can handle those elsewhere.

**Comment by visajshah** [comment]
Hey @reinecke and @jminor, requesting a review of the attached PR.
