### ISSUE TITLE
Documentation Request for Ranges

### ISSUE THREAD

**Issue by boredstiff** [AcademySoftwareFoundation/OpenTimelineIO#1347]
## Feature Request

Replace TODOs in Documentation for Ranges with explanations.

## Description

I was reading through the documentation on Ranges and noticed a lot of TODOs on different schema items are still present. I searched through the issues and did not see another issue filed that mentioned this. I do not presently have any questions that need to be answered regarding these Ranges as I am just reading through the docs, but thought it might be good to point it out. 

## Context

https://github.com/AcademySoftwareFoundation/OpenTimelineIO/blob/main/docs/tutorials/time-ranges.md

Thank you.

**Comment by meshula** [comment]
Thanks for noticing the todo's, I added some labels.
