### ISSUE TITLE
Add ImageSequenceReference support to File bunder adapters (OTIO[d|z]) 

### ISSUE THREAD

**Issue by ssteinbach** [AcademySoftwareFoundation/OpenTimelineIO#1380]
Currently the file bundle adapters only support external references:
https://github.com/AcademySoftwareFoundation/OpenTimelineIO/blob/6cd4161aa3adfbca6544798158a8b5f006235f6b/src/py-opentimelineio/opentimelineio/adapters/file_bundle_utils.py#L113

ImageSequenceReferences that can resolve to files on disk should also be supportable by MediaReferences.

**Comment by timlehr** [comment]
This draft PR from @darbyjohnston addresses this: https://github.com/AcademySoftwareFoundation/OpenTimelineIO/pull/1627

Issue is duplicated in https://github.com/AcademySoftwareFoundation/OpenTimelineIO/issues/1621
