### ISSUE TITLE
OTIO for Python 3.10 on Pypi

### ISSUE THREAD

**Issue by werwack** [AcademySoftwareFoundation/OpenTimelineIO#1394]
## Feature Request
Making a wheel of OTIO for Python 3.10 available on Pypi 

## Description
I'm the author of [Ubisoft Shot Manager](https://ubisoft-shotmanager.readthedocs.io/en/latest/), an add-on for Blender to do previz and storyboarding. This add-on relies on OpentimelineIO to import and export edits.
Since version 3.2, the Blender Python version is 3.10, hence my request a few months ago to support this version. Your help to create a new wheel was very appreciated.
In order to allow the installation on the users' computers I had to add the wheel in the add-on package. And to avoid to make it too heavy I just add the Windows package (which still weights 5Mo!).

It would be considerably easier for us and the add-on users of all platforms if all the wheels were available on Pypi.

Thank you ;)

**Comment by ssteinbach** [comment]
We're planning on making a new release of OTIO within the next month from the top of the master branch.  That release should include python 3.10 support, as well as other fixes from this beta cycle (full list: https://github.com/AcademySoftwareFoundation/OpenTimelineIO/milestone/16?closed=1 ).  I'll double check with @JeanChristopheMorinPerso, but I believe all of that stuff (including pypi upload) should happen automatically once we poke the release buttons.  Would that work for you?

Also, that looks like a neat tool.  Thanks for sharing and reaching out!

**Comment by JeanChristopheMorinPerso** [comment]
Yep, everything should be automatic. Python 3.10 has been part of our build matrix for a while and every build generates Python 3.10 wheels. It's just  a matter of triggering a release, like @ssteinbach said.

**Comment by eliot-lightcraft** [comment]
Triggering the release would be extremely helpful. I'm also working with Blender Python 3.10. Any chance to do this in the next few days?

**Comment by ssteinbach** [comment]
Sorry, the next couple of days won't be possible, but within the next month.

**Comment by werwack** [comment]
Thank you very much 👍
Any time will do for me, that's really helpful to have this ETA though.

**Comment by ssteinbach** [comment]
The wheels should be live now on PyPI.
