### ISSUE TITLE
Drop Python2.7 support

### ISSUE THREAD

**Issue by ssteinbach** [AcademySoftwareFoundation/OpenTimelineIO#1395]
As noted by #1094, VFX platform 2019 is the last VFX platform that includes python 2.7.  This issue is to prepare for when we drop python 2.7 support.

- [ ] update check in setup.py: 
  - [ ] https://github.com/AcademySoftwareFoundation/OpenTimelineIO/blob/78941ddf12a16e6b3495290e7c920ce674b1f342/setup.py#L186
  - [ ] https://github.com/AcademySoftwareFoundation/OpenTimelineIO/blob/78941ddf12a16e6b3495290e7c920ce674b1f342/setup.py#L295
  - [ ] https://github.com/AcademySoftwareFoundation/OpenTimelineIO/blob/78941ddf12a16e6b3495290e7c920ce674b1f342/setup.py#L336
- [ ] update README.md
- [ ] update files that reference 2.7, especially places marked `# python2` or `# python 2.7`  (this is a rough list from grep)
```
tests/test_builtin_adapters.py
tests/test_console.py
tests/test_timeline.py
tests/test_cmx_3600_adapter.py
tests/test_otioz.py
tests/test_adapter_plugin.py
tests/baselines/plugin_module/otio_mockplugin/__init__.py
tests/test_hooks_plugins.py
tests/test_examples.py
contrib/opentimelineio_contrib/adapters/tests/test_hls_playlist_adapter.py
src/py-opentimelineio/opentimelineio/adapters/file_bundle_utils.py
src/py-opentimelineio/opentimelineio/adapters/otiod.py
src/py-opentimelineio/opentimelineio/adapters/fcp_xml.py
src/py-opentimelineio/opentimelineio/url_utils.py
```
- [ ] update `.github/workflows/python-package.yml` - [python-package.yml](https://github.com/AcademySoftwareFoundation/OpenTimelineIO/blob/main/.github/workflows/python-package.yml)
- [ ] update pybind11 to 2.10+
- [ ] try [pyupgrade](https://github.com/asottile/pyupgrade) to move to newer syntax where available

**Comment by JeanChristopheMorinPerso** [comment]
Do we also want to update the code base to use newer syntax? If so then we can use https://github.com/asottile/pyupgrade to automatically upgrade code to use newer syntax. It also handles changing imports, and a bunch of different things. When running the tool, you basically tell it to target a specific Python version and it will take care of the rest.

**Comment by JeanChristopheMorinPerso** [comment]
We might also want to update Pybind11 to 2.10+.

**Comment by meshula** [comment]
it would be interesting to try pyupgrade and see what happens, and yes we'll want to update pybind11 to latest. we've been frozen for a whle

**Comment by ssteinbach** [comment]
@JeanChristopheMorinPerso great suggestion.  It sounds like we want to do this after making release `0.15.0`.

**Comment by ssteinbach** [comment]
(I added your notes as todo list items)
