### ISSUE TITLE
SerializableCollection::children_if doesn't recurse correctly 

### ISSUE THREAD

**Issue by ssteinbach** [AcademySoftwareFoundation/OpenTimelineIO#1400]
## C++ Repro

the assertion at the end of this program fails:

```c++
#include <iostream>

#include "opentimelineio/clip.h"
#include "opentimelineio/errorStatus.h"
#include "opentimelineio/serializableObject.h"
#include "opentimelineio/track.h"
#include "opentimelineio/timeline.h"
#include "opentimelineio/serializableCollection.h"

namespace otio = opentimelineio::OPENTIMELINEIO_VERSION;

int
main(void)
{
    opentimelineio::v1_0::ErrorStatus err;

    // make a clip
    otio::SerializableObject::Retainer<otio::Clip> cl = new otio::Clip();

    // put it in a track
    otio::SerializableObject::Retainer<otio::Track> tr = new otio::Track();
    tr->append_child(cl);
    
    // check track
    auto result = tr->children_if<otio::Clip>(&err);
    assert (result.size() == 1);
    result.clear();

    // Make a timeline and add the track
    otio::SerializableObject::Retainer<otio::Timeline> tl = new otio::Timeline();
    tl->tracks()->append_child(tr);

    result = tl->children_if<otio::Clip>(&err);
    assert (result.size() == 1);
    result.clear();

    // Make a serializableCollection and then add the timeline
    otio::SerializableObject::Retainer<otio::SerializableCollection> sc = new otio::SerializableCollection();
    result = sc->children_if<otio::Clip>(&err, {}, false);

    // fail
    assert (result.size() == 1);
    result.clear();

    std::cout << "success" << std::endl;
}
```

## Python Repro
```python
import opentimelineio as otio

cl = otio.schema.Clip()

tr = otio.schema.Track()
tr.append(cl)

assert len(tr.clip_if()) == 1

tl = otio.schema.Timeline()
tl.tracks.append(tr)

assert len(tl.clip_if()) == 1

sc = otio.schema.SerializableCollection()
sc.append(tl)

# fails
assert len(sc.clip_if()) == 1
```

## Parameters are not wrapped

Note that despite the comment/argument here:
https://github.com/AcademySoftwareFoundation/OpenTimelineIO/blob/8cdda64f5ef924855ce503822e1aeb125e6b011e/src/py-opentimelineio/opentimelineio/schema/track.py#L6

The `shallow_search` parameter is not passed through to the C++ function.

## Related
-  `shallow_search` parameter does not appear to be exposed to python
- there appear to be no python tests that call `clip_if` and the only test that calls `children_if` is the cmx_edl tests

## Items
- [ ] bug in `SerializableCollection::children_if` (should find the clip in the test above)
- [ ] exposing parameters of `clip_if` / `children_if`
- [ ] add python unit tests for `clip_if` and `children_if`

**Comment by darbyjohnston** [comment]
It looks like ```SerializableCollection::children_if``` needs an additional condition for ```Timeline``` types, it currently only searches inside ```SerializableCollection``` and ```Composition``` types.

Though the class hierarchy makes it confusing since there are three different container types each with their own ```children_if```. Also the child types are different so I guess a ```Timeline``` cannot have a ```SerializableCollection``` child? It also looks like the ```search_range``` argument to ```SerializableCollection::children_if``` doesn't apply to children of the ```SerializableCollection```.

**Comment by ssteinbach** [comment]
Right:

- Serializable collection can contain any serializable object, without any temporal relationship
- The two temporally-related containers are stacks, which can contain items but not transitions, 
- ...and tracks (sequences) which can can items and transitions

example:
```python

import opentimelineio as otio

# the collection
sc = otio.schema.SerializableCollection()

# things that can go into it, any kind of SerializableObject
demo_objects = [
    otio.schema.Clip(),
    otio.schema.Track(),
    otio.schema.Timeline(),
    otio.schema.Transition(),
    otio.schema.ExternalReference(),
    otio.core.SerializableObject(),
]

for thing in demo_objects:
    sc.append(thing)

for thing in sc:
    print(type(thing))
```
produces:
```bash
<class 'opentimelineio._otio.Clip'>
<class 'opentimelineio._otio.Track'>
<class 'opentimelineio._otio.Timeline'>
<class 'opentimelineio._otio.Transition'>
<class 'opentimelineio._otio.ExternalReference'>
<class 'opentimelineio._otio.SerializableObject'>
```

**Comment by darbyjohnston** [comment]
I created a PR with a possible fix and your C++ test. I marked it as a draft for now since it doesn't address the other items yet (Python tests and missing arguments).

**Comment by ssteinbach** [comment]
I think this is worth getting into the next release, if you think you'll have a fix for it quickly.  I also need to resolve the build issues with #1403
