### ISSUE TITLE
Support for VFX Reference Platform 2022

### ISSUE THREAD

**Issue by jminor** [AcademySoftwareFoundation/OpenTimelineIO#1467]
With the compiler upgrades in [VFX Reference Platform 2022](https://vfxplatform.com), we should be able to build OTIO with std::any and std::optional instead of [depending on any and optional-lite](https://github.com/AcademySoftwareFoundation/OpenTimelineIO/tree/main/src/deps).

We should ensure that OTIO can compile against C++17 without those dependencies and provide an option to opt in/out of that change.

**Comment by JeanChristopheMorinPerso** [comment]
Related to https://github.com/AcademySoftwareFoundation/OpenTimelineIO/issues/1094.

**Comment by darbyjohnston** [comment]
I think this can be closed now that we have updated to C++17?
