### ISSUE TITLE
Use the standard library fabs()

### ISSUE THREAD

**Issue by darbyjohnston** [AcademySoftwareFoundation/OpenTimelineIO#1495]
I noticed there is a custom implementation of ```fabs()``` in ```rationalTime.h```, it might be nice to replace it with the function from the standard library:
https://en.cppreference.com/w/cpp/numeric/math/fabs

It would reduce the amount of code in OpenTime and remove a function that should probably not be part of the API.

**Comment by darbyjohnston** [comment]
Oops, now I remember why there is a need for the custom implementation. It uses ```constexpr``` which is not available from the standard library until C++23. I'll create a separate PR to add a comment about this.

**Comment by meshula** [comment]
@darbyjohnston  It wasn't just constexpr, although that is the comment on the commit. We wanted specific behavior around nan and inf.

To quote the C spec

```
An implementation may give zero and non-numeric values (such as infinities and NaNs) a sign or may leave them unsigned. Wherever such values are unsigned, any requirement in this International Standard to retrieve the sign shall produce an unspecified sign, and any requirement to set the sign shall be ignored.
```

There was a corner case sadly not captured in a regression test, where signs were not propagating as expected. Maybe someone else recalls more specific details. As I recall, this bit masking implementation was a deliberate choice in order to avoid underspecified behavior in the C spec.

**Comment by darbyjohnston** [comment]
Interesting, we should probably add a comment that explains this. I had forgotten and my first instinct seeing it again was that it was possibly duplicated code. Also should it be a part of the public API?

**Comment by meshula** [comment]
It's only in the public API because of the constexpr business. It could be made private copied twice within RationalTime and TimeRange. I'd have no argument with that, as I do concur with your implication that it is an implementation detail.

**Comment by darbyjohnston** [comment]
It would be nice to hide but I'm not a fan of duplicating the code even though it's a fairly small function. Another way of hiding it would be as a protected function in a base class but that seems a bit convoluted. I think just a comment explaining it's use would be good, I'll make a separate PR for that.

I wonder if GPT3 could write Doxygen for us. :)

**Comment by meshula** [comment]
I think GPT3 could in fact write documentation for us, or to put it a different way, it could write a rather prosey explanation that might provide a good starting point for clearly explaining what some code does. You can grab a function and ask it "Explain the following code: <paste code>". Josh has been experimenting with it.
