### ISSUE TITLE
Support for C++17

### ISSUE THREAD

**Issue by meshula** [AcademySoftwareFoundation/OpenTimelineIO#1526]
## Support for C++ 17

VfxPlatform CY2020 specifies C++14, but CY2021 and greater specify C++17.
We currently use c++17 shim libraries to get the functionality of optional and any.
Adopting C++17 would eliminate two dependencies from our build and thus simplify our build scripts, and simplify our build configuration.

## Description

When the next OpenTimelineIO release is tagged, we will note that it is the last release supporting CY2020.
We will go ahead at that point with removing the optional and any shims.
Should bugs arise that need to be addressed in that release for the CY2020 platform, we will create a maintenance branch and perform corrections as required in that branch. Subsequent point releases in support of CY2020 will be made against that branch.
Support for CY2020 will be dropped at the end of calendar year 2023.

## Context

Participants representing studios and vendors queried in the 2023 Jan 19 TSC meeting indicate they already building with C++17.

**Comment by darbyjohnston** [comment]
As I mentioned on Slack I'm happy to work on this when it's ready. It there an ETA for the next release?

**Comment by meshula** [comment]
Hi Darby, I think it would be fine to start on this as a feature branch.

As to an ETA for the next release, I started a discussion here https://github.com/AcademySoftwareFoundation/OpenTimelineIO/discussions/1527 since I can't readily answer your question.
