### ISSUE TITLE
Python 3 syntax upgrade

### ISSUE THREAD

**Issue by jminor** [AcademySoftwareFoundation/OpenTimelineIO#1528]
Now that OTIO has dropped support for Python 2, we could upgrade a bunch of the Python code to more modern syntax. There is an automated tool (maybe others too) which makes this very easy. https://github.com/asottile/pyupgrade

Note: We should probably wait until after #1386 is done to avoid complicating the landing of the `extract_adapters` branch.

**Comment by JeanChristopheMorinPerso** [comment]
If I'm not mistaken, we ran it when we removed py2 from the codebase. Am I right @ssteinbach ?

**Comment by jminor** [comment]
Oh, you're right we did this already! I was looking at something old by mistake.

**Comment by JeanChristopheMorinPerso** [comment]
ah ok. We could probably use the occasion to run it in CI of it's fast enough. That would allow us to enforce f-strings, etc.
