### ISSUE TITLE
opentimelineio won't import in an embedable Python interpreter

### ISSUE THREAD

**Issue by robbiesz** [AcademySoftwareFoundation/OpenTimelineIO#1548]
### Incorrect Functionality and General Questions

git commit d48163e4 introduced a change to omit external functions (ie functions from the python built-in `collections_abc` module) from the sphinx documentation.
The logic expects these functions to have \_\_doc\_\_ properties and performs a += operation to append the necessary tag for sphinx.

However embeddable python (eg. https://www.python.org/ftp/python/3.7.9/python-3.7.9-embed-amd64.zip) ships with only byte-code compiled versions of its built-in functions - including the collections module. pyc files do not contain docstrings, so as a result those functions will have \_\_doc\_\_ set to None and no string concatenation is possible.

I would like to submit a PR with the fix. Please let me know the next steps.

## To Reproduce

1. Operating System: Windows
2. Python version: Embeddable/portable 3.7.x and 3.9.x
3. Example snippet that demonstrates the issue - if it's a build issue,
    import opentimelineio

5. OpenTimelineIO release version or commit hash: 0.15.0
6. Compiler information: N/A, I've used prebuilt python wheel from pypi

## Expected Behavior

I expect that `import opentimelineio` succeeds.

## Screenshots

```
C:\Users\robsz\AppData\Local\Programs\al-editron-beta\resources\python>dist\python.exe -c "import opentimelineio"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\robsz\AppData\Local\Programs\al-editron-beta\resources\python\dist\dependencies\opentimelineio\__init__.py", line 14, in <module>
    from . import (
  File "C:\Users\robsz\AppData\Local\Programs\al-editron-beta\resources\python\dist\dependencies\opentimelineio\core\__init__.py", line 35, in <module>
    from . _core_utils import ( # noqa
  File "C:\Users\robsz\AppData\Local\Programs\al-editron-beta\resources\python\dist\dependencies\opentimelineio\core\_core_utils.py", line 407, in <module>
    _add_mutable_mapping_methods(AnyDictionary)
  File "C:\Users\robsz\AppData\Local\Programs\al-editron-beta\resources\python\dist\dependencies\opentimelineio\core\_core_utils.py", line 239, in _add_mutable_mapping_methods
    getattr(mapClass, name).__doc__ += '\n\n:meta private:'
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'
```

**Comment by meshula** [comment]
Thanks for the report!

> next steps?

Basically the summary of next steps would be, register with EasyCLA, fork this repo, prepare a fix, submit a PR.

If you would like to discuss your proposed fix here first, or in our Slack, or at a TSC meeting, those are also possibilities.

**Comment by robbiesz** [comment]
I had a look through the code and \_\_doc\_\_ is only blind-concatenated twice in the same module (_core_utils.py)

I was thinking of a really, trivial fix:

```
diff --git a/src/py-opentimelineio/opentimelineio/core/_core_utils.py b/src/py-opentimelineio/opentimelineio/core/_core_utils.py
index df2a075..32f2519 100644
--- a/src/py-opentimelineio/opentimelineio/core/_core_utils.py
+++ b/src/py-opentimelineio/opentimelineio/core/_core_utils.py
@@ -177,7 +177,9 @@ def _add_mutable_mapping_methods(mapClass):
 
                 # Hide the method frm Sphinx doc.
                 # See https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#info-field-lists  # noqa
-                getattr(mapClass, name).__doc__ += '\n\n:meta private:'
+                getattr(mapClass, name).__doc__ = "{}\n\n:meta private:".format(
+                    getattr(mapClass, name).__doc__ or ""
+                )
 
     mapClass.setdefault = setdefault
     mapClass.pop = pop
@@ -329,7 +331,9 @@ def _add_mutable_sequence_methods(
 
                     # Hide the method frm Sphinx doc.
                     # See https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#info-field-lists  # noqa
-                    getattr(sequenceClass, name).__doc__ += '\n\n:meta private:'
+                    getattr(sequenceClass, name).__doc__ = "{}\n\n:meta private:".format(
+                        getattr(sequenceClass, name).__doc__ or ""
+                    )
 
     if not issubclass(sequenceClass, SerializableObject):
         def __copy__(self):
```

Thoughts?

I need to look into what EasyCLA is.

**Comment by JeanChristopheMorinPerso** [comment]
EasyCLA is a Linux Foundation bot/service for CLA (CLA stands for contributor license agreement). The easiest way is to create a PR, and the bot will create a comment on the PR with a link to sign the CLA. It's also possible to pre-sign it before creating a PR, but I'll be frank, I'm not too sure how to do this.

Note that there is two types of CLA. Individual CLA and Corporate CLA. Depending on your situation, your employer might need to sign the corporate one.

See https://docs.linuxfoundation.org/lfx/easycla for more details on EasyCLA.

Please let us know if you have any questions!

**Comment by JeanChristopheMorinPerso** [comment]
Actually, the instructions on how to send a signed CLA to OTIO without creating a PR can be found at https://github.com/AcademySoftwareFoundation/OpenTimelineIO/blob/main/CONTRIBUTING.md#contributor-license-agreement.

**Comment by meshula** [comment]
Also, for a very small change like that, we can make the change for you, if you give us permission. I'm not a Python expert though, so I'd want to get one of our experts to approve the change or provide feedback.

**Comment by robbiesz** [comment]
@JeanChristopheMorinPerso I've tried to push my branch to origin but got a permission denied message. Likely, I would have to email the CLA in to get permission to push.

@meshula By all means! Feel free to commit the change yourselves. My goal is to be able to use OTIO in our environment. However I would be interested in getting feedback on the change from the python gurus.

**Comment by apetrynet** [comment]
@robbiesz, sorry if I'm misinterpreting here, but you can't push directly to this repository. 
You'll have to create a pull request via a fork of OTIO under your own user space.

**Comment by robbiesz** [comment]
@apetrynet Thanks for the directions! I have managed to fork the repo and I was able to push the branch and open the PR #1550  but when I try to sign the CLA, I get an error both Corporate and Individual user options:
``` The Individual CLA option is not enabled for this project. Please to your administrator to enable the Individual CLA option for this project.
```
Can you assist please?

**Comment by apetrynet** [comment]
Glad to hear you got a bit further. However, I'm not sure I'm able to solve the CLA issue. 

Individuals should be able to sign. I'll add @jminor and @jmertic to the mix here.

**Comment by robbiesz** [comment]
It's sorted now. I managed to sign the CLA. Thank you!
