### ISSUE TITLE
[RFE] otioview refresh feature

### ISSUE THREAD

**Issue by waldirio** [AcademySoftwareFoundation/OpenTimelineIO#1559]
## Feature Request
Add refresh feature on otioview screen

## Description
Currently, we can start our coding and eventually, open `otioview` to check the current work, tracks, clips, etc. However, for any new change, we need to close and open a new instance of `otioview` against the `.otio` file.

The main idea should be to add the feature to refresh the `otioview` automatically, or with a customer interaction, for example F5 or refresh button. In this way, we can keep `otioview` open in one screen, keep working/developing in a different terminal, and once we update the `.otio` file, we can see automatically the changes on `otioview` screen with no necessary to open a new one once again and again :)

Thank you!
Waldirio

**Comment by jminor** [comment]
We are hoping to replace otioview with [Raven](https://github.com/OpenTimelineIO/raven) sometime soon.
 Raven has a "Revert" menu item which does exactly what you are looking for. Could you give that a try to see if it works for you?

<img width="600" alt="image" src="https://user-images.githubusercontent.com/169599/223192853-721dea10-f045-400e-87c6-016dee3ca854.png">

**Comment by reinecke** [comment]
Closing because Raven (the future OTIOView) supports this. Please re-open if I missed something.
