### ISSUE TITLE
possible problem with gcc visibility decorations?

### ISSUE THREAD

**Issue by meshula** [AcademySoftwareFoundation/OpenTimelineIO#1569]
I think there may be an issue with visibility decorations on string exports on gcc?

Looking at the CI results on the C bindings

https://github.com/OpenTimelineIO/OpenTimelineIO-C-Bindings/actions

it seems that some exported strings are getting multiply-defined. Has anyone got insight into the issue seen there? I believe we probably need a fix here to address it.

**Comment by JeanChristopheMorinPerso** [comment]
@meshula is it the same issue as https://github.com/OpenTimelineIO/OpenTimelineIO-C-Bindings/issues/22?

**Comment by meshula** [comment]
Every time it comes up, I think I end up asking if anyone's able to offer help LOL. My suggestion last time was to replace the externed strings with accessor functions. I just keep hoping that eventually someone will have a simple non-intrusive fix, as my suggestion involves an API change.

**Comment by reinecke** [comment]
Closing as fixed under the [C bindings #22](https://github.com/OpenTimelineIO/OpenTimelineIO-C-Bindings/issues/22) fix. There is more we could do on this (visibility decorators), however we can bring that as a separate issue later.
