### ISSUE TITLE
X

### ISSUE THREAD

**Issue by Sxxvega** [AcademySoftwareFoundation/OpenTimelineIO#1581]
## Feature Request

Is this a New Feature, or a Proposed Change to existing Behavior?

## Description

Describe the new feature, or describe the modification to existing behavior, and provide context as necessary to help with understanding how the feature relates to a workflow or functionality.

## Context

Add any other context here, such as simulated output, or screenshots, that might help clarify the request.

**Comment by apetrynet** [comment]
Closing issue as it doesn't contain any information. Please submit a new feature request with information as described in the template if you have a feature request.
