### ISSUE TITLE
Add support for image sequences when creating .otioz files with otioconvert

### ISSUE THREAD

**Issue by darbyjohnston** [AcademySoftwareFoundation/OpenTimelineIO#1621]
It looks like image sequences are not supported when creating .otioz files with otioconvert? I tried converting an .otio file with an image sequence and it looks like the images were not bundled:
```
> zipinfo SingleClipSeq.otioz
Archive:  SingleClipSeq.otioz
Zip file size: 819 bytes, number of entries: 2
?rw-------  2.0 unx        5 b- defN 23-Jun-10 16:45 version.txt
?rw-------  2.0 unx     3185 b- defN 23-Jun-10 16:45 content.otio
2 files, 3190 bytes uncompressed, 599 bytes compressed:  81.2%
```

Looking at the code in ```file_bundile_utils.py``` there is this comment:
```
try:
    target_url = cl.media_reference.target_url
except AttributeError:
    # not an ExternalReference, ignoring it.
    continue
```

It would be nice to add support for image sequences or maybe add a warning that they are being ignored.

**Comment by darbyjohnston** [comment]
Also it looks like the code in ```file_bundle_utils.py``` only calls ```media_reference()```, so maybe multiple media references are also not supported yet?

**Comment by meshula** [comment]
I believe the state of the discussion is that we'd like such bundling were someone to add it to otioconvert.

**Comment by darbyjohnston** [comment]
Closing this, since there doesn't seem to be any interest (PR open for > 15 months).
