### ISSUE TITLE
fcp_xml adapter 

### ISSUE THREAD

**Issue by BorisMolchanov** [AcademySoftwareFoundation/OpenTimelineIO#1631]
It looks like the if/elif clause starting at line 1459 is doesn't account for `ImageSequenceReferences`. 
[fcp_xml.py#L1459](https://github.com/AcademySoftwareFoundation/OpenTimelineIO/blob/45c6cfdd2013a270303af6d5ed82887c8d23affc/src/py-opentimelineio/opentimelineio/adapters/fcp_xml.py#L1459)

When I try to create a timeline using the XML adapter, I get this error: 

> line 1492, in _build_file
    text=(media_reference.name or fallback_file_name),
UnboundLocalError: local variable 'fallback_file_name' referenced before assignment

It's look like it's impossible to create correct XML with timeline from image sequence now.

**Comment by reinecke** [comment]
It looks like issue #1092 covers this issue already. Closing this as a duplicate and copying the new points over there.
Thanks for reporting!
