### ISSUE TITLE
OTIO edit commands

### ISSUE THREAD

**Issue by ggarra13** [AcademySoftwareFoundation/OpenTimelineIO#1649]
## Feature Request

This is a feature request to add editing commands based on #711 and experimental PR #1518.

## Description

I am currently working on adding all the commands described in #711, without Undo/Redo capabilities and, as a first step, without taking into account transitions.  I am currently adding them to a new namespace (edit), instead of algo as it was discussed.

## Context

I currently have (with unit tests):  slice, overwrite, insert, slip, slide and (without checking available_range) trim.
I am still missing: finishing trim, and work on ripple, roll and fill.

**Comment by timlehr** [comment]
Seems like this one is fully done now @reinecke.
