### ISSUE TITLE
find_children is broken with two tracks.

### ISSUE THREAD

**Issue by ggarra13** [AcademySoftwareFoundation/OpenTimelineIO#1652]
### Incorrect Functionality and General Questions

C++'s timeline->find_children<otio::Item> is broken when there are two tracks and a search range is involved.

## To Reproduce

I created a PR for a test for it to show both the correct and incorrect functionality.  I am also attaching the test here as .txt file.

[test_find_children.cpp.txt](https://github.com/AcademySoftwareFoundation/OpenTimelineIO/files/12388154/test_find_children.cpp.txt)

## Expected Behavior

timeline->find_children<otio::Item>() should return all otio::Items in the range.

**Comment by darbyjohnston** [comment]
Thanks for creating this test! I created a new PR (#1766) that has a potential fix and and the test, so I'll close this one.

**Comment by ggarra13** [comment]
Darby, would you be a darling and test Issue #1750? I've been wanting to attend the OTIO meetings and for one reason or another I cannot make it.
Issue #1750 is an incorrect functionality between M1 and M3 machines, which seems like a macOS compiler issue.  I don't have any M1/M3 machine but I would like to know if the test works fine on an M1 machine at least.
