### ISSUE TITLE
otiotool --redact doesn't redact media reference names

### ISSUE THREAD

**Issue by jminor** [AcademySoftwareFoundation/OpenTimelineIO#1678]
### Incorrect Functionality

otiotool's `--redact` feature is supposed to remove all potentially sensitive information from an OTIO file, however it leaves the "name" attribute of MediaReference objects as-is. This could potentially reveal information about project names, talent, locations, dates, etc. which might be sensitive.

## To Reproduce

[redacted_media_out_of_bounds.otio.zip](https://github.com/AcademySoftwareFoundation/OpenTimelineIO/files/13245861/redacted_media_out_of_bounds.otio.zip)

1. Download attached OTIO file, which is already redacted, but still has media reference names.
2. Run `otiotool -i input.otio --redact -o output.otio
3. Notice that output.otio still has names like "i345_13c" in it.

## Expected Behavior

Media reference names should be replaced with anonymous names like "Media Reference #7".

**Comment by apetrynet** [comment]
Fixed in PR #1712
