### ISSUE TITLE
Unable to build Wheel

### ISSUE THREAD

**Issue by Aiacos** [AcademySoftwareFoundation/OpenTimelineIO#1686]
Ubuntu 23.10

 pip install OpenTimelineIO
Collecting OpenTimelineIO
  Downloading OpenTimelineIO-0.15.0.tar.gz (5.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 8.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pyaaf2<1.7,>=1.4 (from OpenTimelineIO)
  Downloading pyaaf2-1.6.0-py2.py3-none-any.whl (103 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 103.6/103.6 kB 5.1 MB/s eta 0:00:00
Building wheels for collected packages: OpenTimelineIO
  Building wheel for OpenTimelineIO (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for OpenTimelineIO (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [225 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-311
      creating build/lib.linux-x86_64-cpython-311/opentimelineio
      copying src/py-opentimelineio/opentimelineio/versioning.py -> build/lib.linux-x86_64-cpython-311/opentimelineio
      copying src/py-opentimelineio/opentimelineio/test_utils.py -> build/lib.linux-x86_64-cpython-311/opentimelineio
      copying src/py-opentimelineio/opentimelineio/media_linker.py -> build/lib.linux-x86_64-cpython-311/opentimelineio
      copying src/py-opentimelineio/opentimelineio/opentime.py -> build/lib.linux-x86_64-cpython-311/opentimelineio
      copying src/py-opentimelineio/opentimelineio/hooks.py -> build/lib.linux-x86_64-cpython-311/opentimelineio
      copying src/py-opentimelineio/opentimelineio/__init__.py -> build/lib.linux-x86_64-cpython-311/opentimelineio
      copying src/py-opentimelineio/opentimelineio/url_utils.py -> build/lib.linux-x86_64-cpython-311/opentimelineio
      copying src/py-opentimelineio/opentimelineio/exceptions.py -> build/lib.linux-x86_64-cpython-311/opentimelineio
      creating build/lib.linux-x86_64-cpython-311/opentimelineio/algorithms
      copying src/py-opentimelineio/opentimelineio/algorithms/track_algo.py -> build/lib.linux-x86_64-cpython-311/opentimelineio/algorithms
      copying src/py-opentimelineio/opentimelineio/algorithms/stack_algo.py -> build/lib.linux-x86_64-cpython-311/opentimelineio/algorithms
      copying src/py-opentimelineio/opentimelineio/algorithms/timeline_algo.py -> build/lib.linux-x86_64-cpython-311/opentimelineio/algorithms
      copying src/py-opentimelineio/opentimelineio/algorithms/filter.py -> build/lib.linux-x86_64-cpython-311/opentimelineio/algorithms
      copying src/py-opentimelineio/opentimelineio/algorithms/__init__.py -> build/lib.linux-x86_64-cpython-311/opentimelineio/algorithms
      creating build/lib.linux-x86_64-cpython-311/opentimelineio/plugins
      copying src/py-opentimelineio/opentimelineio/plugins/python_plugin.py -> build/lib.linux-x86_64-cpython-311/opentimelineio/plugins
      copying src/py-opentimelineio/opentimelineio/plugins/__init__.py -> build/lib.linux-x86_64-cpython-311/opentimelineio/plugins
      copying src/py-opentimelineio/opentimelineio/plugins/manifest.py -> build/lib.linux-x86_64-cpython-311/opentimelineio/plugins
      creating build/lib.linux-x86_64-cpython-311/opentimelineio/console
      copying src/py-opentimelineio/opentimelineio/console/otiostat.py -> build/lib.linux-x86_64-cpython-311/opentimelineio/console
      copying src/py-opentimelineio/opentimelineio/console/autogen_serialized_datamodel.py -> build/lib.linux-x86_64-cpython-311/opentimelineio/console
      copying src/py-opentimelineio/opentimelineio/console/autogen_version_map.py -> build/lib.linux-x86_64-cpython-311/opentimelineio/console
      copying src/py-opentimelineio/opentimelineio/console/console_utils.py -> build/lib.linux-x86_64-cpython-311/opentimelineio/console
      copying src/py-opentimelineio/opentimelineio/console/autogen_plugin_documentation.py -> build/lib.linux-x86_64-cpython-311/opentimelineio/console
      copying src/py-opentimelineio/opentimelineio/console/otioconvert.py -> build/lib.linux-x86_64-cpython-311/opentimelineio/console
      copying src/py-opentimelineio/opentimelineio/console/otiopluginfo.py -> build/lib.linux-x86_64-cpython-311/opentimelineio/console
      copying src/py-opentimelineio/opentimelineio/console/otiocat.py -> build/lib.linux-x86_64-cpython-311/opentimelineio/console
      copying src/py-opentimelineio/opentimelineio/console/otiotool.py -> build/lib.linux-x86_64-cpython-311/opentimelineio/console
      copying src/py-opentimelineio/opentimelineio/console/__init__.py -> build/lib.linux-x86_64-cpython-311/opentimelineio/console
      creating build/lib.linux-x86_64-cpython-311/opentimelineio/adapters
      copying src/py-opentimelineio/opentimelineio/adapters/file_bundle_utils.py -> build/lib.linux-x86_64-cpython-311/opentimelineio/adapters
      copying src/py-opentimelineio/opentimelineio/adapters/otio_json.py -> build/lib.linux-x86_64-cpython-311/opentimelineio/adapters
      copying src/py-opentimelineio/opentimelineio/adapters/otioz.py -> build/lib.linux-x86_64-cpython-311/opentimelineio/adapters
      copying src/py-opentimelineio/opentimelineio/adapters/fcp_xml.py -> build/lib.linux-x86_64-cpython-311/opentimelineio/adapters
      copying src/py-opentimelineio/opentimelineio/adapters/otiod.py -> build/lib.linux-x86_64-cpython-311/opentimelineio/adapters
      copying src/py-opentimelineio/opentimelineio/adapters/__init__.py -> build/lib.linux-x86_64-cpython-311/opentimelineio/adapters
      copying src/py-opentimelineio/opentimelineio/adapters/svg.py -> build/lib.linux-x86_64-cpython-311/opentimelineio/adapters
      copying src/py-opentimelineio/opentimelineio/adapters/cmx_3600.py -> build/lib.linux-x86_64-cpython-311/opentimelineio/adapters
      copying src/py-opentimelineio/opentimelineio/adapters/adapter.py -> build/lib.linux-x86_64-cpython-311/opentimelineio/adapters
      creating build/lib.linux-x86_64-cpython-311/opentimelineio/schema
      copying src/py-opentimelineio/opentimelineio/schema/clip.py -> build/lib.linux-x86_64-cpython-311/opentimelineio/schema
      copying src/py-opentimelineio/opentimelineio/schema/effect.py -> build/lib.linux-x86_64-cpython-311/opentimelineio/schema
      copying src/py-opentimelineio/opentimelineio/schema/stack.py -> build/lib.linux-x86_64-cpython-311/opentimelineio/schema
      copying src/py-opentimelineio/opentimelineio/schema/timeline.py -> build/lib.linux-x86_64-cpython-311/opentimelineio/schema
      copying src/py-opentimelineio/opentimelineio/schema/marker.py -> build/lib.linux-x86_64-cpython-311/opentimelineio/schema
      copying src/py-opentimelineio/opentimelineio/schema/external_reference.py -> build/lib.linux-x86_64-cpython-311/opentimelineio/schema
      copying src/py-opentimelineio/opentimelineio/schema/transition.py -> build/lib.linux-x86_64-cpython-311/opentimelineio/schema
      copying src/py-opentimelineio/opentimelineio/schema/generator_reference.py -> build/lib.linux-x86_64-cpython-311/opentimelineio/schema
      copying src/py-opentimelineio/opentimelineio/schema/box2d.py -> build/lib.linux-x86_64-cpython-311/opentimelineio/schema
      copying src/py-opentimelineio/opentimelineio/schema/serializable_collection.py -> build/lib.linux-x86_64-cpython-311/opentimelineio/schema
      copying src/py-opentimelineio/opentimelineio/schema/__init__.py -> build/lib.linux-x86_64-cpython-311/opentimelineio/schema
      copying src/py-opentimelineio/opentimelineio/schema/track.py -> build/lib.linux-x86_64-cpython-311/opentimelineio/schema
      copying src/py-opentimelineio/opentimelineio/schema/schemadef.py -> build/lib.linux-x86_64-cpython-311/opentimelineio/schema
      copying src/py-opentimelineio/opentimelineio/schema/image_sequence_reference.py -> build/lib.linux-x86_64-cpython-311/opentimelineio/schema
      copying src/py-opentimelineio/opentimelineio/schema/v2d.py -> build/lib.linux-x86_64-cpython-311/opentimelineio/schema
      creating build/lib.linux-x86_64-cpython-311/opentimelineio/core
      copying src/py-opentimelineio/opentimelineio/core/item.py -> build/lib.linux-x86_64-cpython-311/opentimelineio/core
      copying src/py-opentimelineio/opentimelineio/core/mediaReference.py -> build/lib.linux-x86_64-cpython-311/opentimelineio/core
      copying src/py-opentimelineio/opentimelineio/core/composable.py -> build/lib.linux-x86_64-cpython-311/opentimelineio/core
      copying src/py-opentimelineio/opentimelineio/core/composition.py -> build/lib.linux-x86_64-cpython-311/opentimelineio/core
      copying src/py-opentimelineio/opentimelineio/core/__init__.py -> build/lib.linux-x86_64-cpython-311/opentimelineio/core
      copying src/py-opentimelineio/opentimelineio/core/_core_utils.py -> build/lib.linux-x86_64-cpython-311/opentimelineio/core
      creating build/lib.linux-x86_64-cpython-311/opentimelineio/schemadef
      copying src/py-opentimelineio/opentimelineio/schemadef/__init__.py -> build/lib.linux-x86_64-cpython-311/opentimelineio/schemadef
      creating build/lib.linux-x86_64-cpython-311/opentimelineview
      copying src/opentimelineview/settings.py -> build/lib.linux-x86_64-cpython-311/opentimelineview
      copying src/opentimelineview/console.py -> build/lib.linux-x86_64-cpython-311/opentimelineview
      copying src/opentimelineview/track_widgets.py -> build/lib.linux-x86_64-cpython-311/opentimelineview
      copying src/opentimelineview/ruler_widget.py -> build/lib.linux-x86_64-cpython-311/opentimelineview
      copying src/opentimelineview/__init__.py -> build/lib.linux-x86_64-cpython-311/opentimelineview
      copying src/opentimelineview/timeline_widget.py -> build/lib.linux-x86_64-cpython-311/opentimelineview
      copying src/opentimelineview/details_widget.py -> build/lib.linux-x86_64-cpython-311/opentimelineview
      creating build/lib.linux-x86_64-cpython-311/opentimelineio_contrib
      copying contrib/opentimelineio_contrib/__init__.py -> build/lib.linux-x86_64-cpython-311/opentimelineio_contrib
      creating build/lib.linux-x86_64-cpython-311/opentimelineio_contrib/adapters
      copying contrib/opentimelineio_contrib/adapters/advanced_authoring_format.py -> build/lib.linux-x86_64-cpython-311/opentimelineio_contrib/adapters
      copying contrib/opentimelineio_contrib/adapters/burnins.py -> build/lib.linux-x86_64-cpython-311/opentimelineio_contrib/adapters
      copying contrib/opentimelineio_contrib/adapters/xges.py -> build/lib.linux-x86_64-cpython-311/opentimelineio_contrib/adapters
      copying contrib/opentimelineio_contrib/adapters/extern_rv.py -> build/lib.linux-x86_64-cpython-311/opentimelineio_contrib/adapters
      copying contrib/opentimelineio_contrib/adapters/extern_maya_sequencer.py -> build/lib.linux-x86_64-cpython-311/opentimelineio_contrib/adapters
      copying contrib/opentimelineio_contrib/adapters/rv.py -> build/lib.linux-x86_64-cpython-311/opentimelineio_contrib/adapters
      copying contrib/opentimelineio_contrib/adapters/kdenlive.py -> build/lib.linux-x86_64-cpython-311/opentimelineio_contrib/adapters
      copying contrib/opentimelineio_contrib/adapters/fcpx_xml.py -> build/lib.linux-x86_64-cpython-311/opentimelineio_contrib/adapters
      copying contrib/opentimelineio_contrib/adapters/hls_playlist.py -> build/lib.linux-x86_64-cpython-311/opentimelineio_contrib/adapters
      copying contrib/opentimelineio_contrib/adapters/ale.py -> build/lib.linux-x86_64-cpython-311/opentimelineio_contrib/adapters
      copying contrib/opentimelineio_contrib/adapters/maya_sequencer.py -> build/lib.linux-x86_64-cpython-311/opentimelineio_contrib/adapters
      copying contrib/opentimelineio_contrib/adapters/__init__.py -> build/lib.linux-x86_64-cpython-311/opentimelineio_contrib/adapters
      copying contrib/opentimelineio_contrib/adapters/ffmpeg_burnins.py -> build/lib.linux-x86_64-cpython-311/opentimelineio_contrib/adapters
      creating build/lib.linux-x86_64-cpython-311/opentimelineio_contrib/adapters/aaf_adapter
      copying contrib/opentimelineio_contrib/adapters/aaf_adapter/aaf_writer.py -> build/lib.linux-x86_64-cpython-311/opentimelineio_contrib/adapters/aaf_adapter
      copying contrib/opentimelineio_contrib/adapters/aaf_adapter/__init__.py -> build/lib.linux-x86_64-cpython-311/opentimelineio_contrib/adapters/aaf_adapter
      copying src/py-opentimelineio/opentimelineio/adapters/builtin_adapters.plugin_manifest.json -> build/lib.linux-x86_64-cpython-311/opentimelineio/adapters
      copying contrib/opentimelineio_contrib/adapters/contrib_adapters.plugin_manifest.json -> build/lib.linux-x86_64-cpython-311/opentimelineio_contrib/adapters
      running build_ext
      -- The C compiler identification is GNU 13.2.0
      -- The CXX compiler identification is GNU 13.2.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Found Python: /opt/zou/zouenv/bin/python (found version "3.11.6") found components: Interpreter Development.Module
      -- Python_INCLUDE_DIRS: /usr/include/python3.11
      -- Python_VERSION: 3.11.6
      -- Building static libs
      -- Install C++ bindings: OFF
      -- Installing Python bindings to: /tmp/pip-install-_dygmynz/opentimelineio_d475d1c48e3c456da038906cf4b8367b/build/lib.linux-x86_64-cpython-311/
      -- Building C++ with Coverage: OFF
      -- Checking git repo is available:
      fatal: .git non è un repository Git (né lo è alcuna delle directory genitrici)
      -- Using src/deps/Imath by default
      CMake Deprecation Warning at src/deps/pybind11/CMakeLists.txt:8 (cmake_minimum_required):        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.

        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.

      -- pybind11 v2.9.2
      -- Performing Test HAS_FLTO
      -- Performing Test HAS_FLTO - Success
      -- Imath is configuring as a cmake sub project
      -- Configure Imath 3.2.0-dev, library API version: 29.0.0
      -- Looking for sin in m
      -- Looking for sin in m - found
      -- Configuring done (0.8s)
      -- Generating done (0.0s)
      -- Build files have been written to: /tmp/pip-install-_dygmynz/opentimelineio_d475d1c48e3c456da038906cf4b8367b/build/temp.linux-x86_64-cpython-311
      [  7%] Building CXX object src/deps/Imath/src/Imath/CMakeFiles/Imath.dir/ImathColorAlgo.cpp.o
      [  7%] Building CXX object src/opentime/CMakeFiles/opentime.dir/errorStatus.cpp.o
      [  7%] Building CXX object src/deps/Imath/src/Imath/CMakeFiles/Imath.dir/half.cpp.o
      [  7%] Building CXX object src/opentime/CMakeFiles/opentime.dir/rationalTime.cpp.o
      [  8%] Building CXX object src/deps/Imath/src/Imath/CMakeFiles/Imath.dir/ImathFun.cpp.o
      In file included from /tmp/pip-install-_dygmynz/opentimelineio_d475d1c48e3c456da038906cf4b8367b/src/opentime/rationalTime.cpp:4:
      /tmp/pip-install-_dygmynz/opentimelineio_d475d1c48e3c456da038906cf4b8367b/src/opentime/rationalTime.h: In function ‘constexpr double opentime::v1_0::fabs(double)’:
      /tmp/pip-install-_dygmynz/opentimelineio_d475d1c48e3c456da038906cf4b8367b/src/opentime/rationalTime.h:27:9: error: ‘uint64_t’ does not name a type
         27 |         uint64_t i;
            |         ^~~~~~~~
      /tmp/pip-install-_dygmynz/opentimelineio_d475d1c48e3c456da038906cf4b8367b/src/opentime/rationalTime.h:10:1: note: ‘uint64_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
          9 | #include <limits>
        +++ |+#include <cstdint>
         10 | #include <string>
      /tmp/pip-install-_dygmynz/opentimelineio_d475d1c48e3c456da038906cf4b8367b/src/opentime/rationalTime.h:29:10: error: ‘union opentime::v1_0::fabs(double)::<unnamed>’ has no member named ‘i’
         29 |     bits.i &= std::numeric_limits<uint64_t>::max() / 2;
            |          ^
      /tmp/pip-install-_dygmynz/opentimelineio_d475d1c48e3c456da038906cf4b8367b/src/opentime/rationalTime.h:29:35: error: ‘uint64_t’ was not declared in this scope
         29 |     bits.i &= std::numeric_limits<uint64_t>::max() / 2;
            |                                   ^~~~~~~~
      /tmp/pip-install-_dygmynz/opentimelineio_d475d1c48e3c456da038906cf4b8367b/src/opentime/rationalTime.h:29:35: note: ‘uint64_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
      /tmp/pip-install-_dygmynz/opentimelineio_d475d1c48e3c456da038906cf4b8367b/src/opentime/rationalTime.h:29:43: error: template argument 1 is invalid
         29 |     bits.i &= std::numeric_limits<uint64_t>::max() / 2;
            |                                           ^
      [ 10%] Building CXX object src/deps/Imath/src/Imath/CMakeFiles/Imath.dir/ImathMatrixAlgo.cpp.o
      gmake[2]: *** [src/opentime/CMakeFiles/opentime.dir/build.make:90: src/opentime/CMakeFiles/opentime.dir/rationalTime.cpp.o] Errore 1
      gmake[1]: *** [CMakeFiles/Makefile2:275: src/opentime/CMakeFiles/opentime.dir/all] Errore 2
      gmake[1]: *** Attesa per i processi non terminati....
      [ 12%] Building CXX object src/deps/Imath/src/Imath/CMakeFiles/Imath.dir/ImathRandom.cpp.o
      [ 14%] Linking CXX static library libImath-3_2.a
      [ 14%] Built target Imath
      gmake: *** [Makefile:136: all] Errore 2
      Traceback (most recent call last):
        File "/opt/zou/zouenv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/zou/zouenv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/zou/zouenv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-b4tfsaws/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 404, in build_wheel
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-b4tfsaws/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 389, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-b4tfsaws/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 279, in <module>
        File "/tmp/pip-build-env-b4tfsaws/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-b4tfsaws/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-b4tfsaws/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-b4tfsaws/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-b4tfsaws/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-b4tfsaws/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-b4tfsaws/overlay/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "/tmp/pip-build-env-b4tfsaws/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-b4tfsaws/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-b4tfsaws/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-b4tfsaws/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-b4tfsaws/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-b4tfsaws/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-b4tfsaws/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 60, in run
        File "<string>", line 76, in build
        File "<string>", line 175, in cmake_install
        File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for OpenTimelineIO
Failed to build OpenTimelineIO
ERROR: Could not build wheels for OpenTimelineIO, which is required to install pyproject.toml-based projects

Thanks,
L.

**Comment by apetrynet** [comment]
Hi @Aiacos!

This looks like a similar issue as in #1685.
OpenTimelineIO 0.15.0 doesn't have wheels built for python 3.11. The upcoming release should include these.

Would you be able to use python 3.10 for the time being?

**Comment by Aiacos** [comment]
I have to downgrade python version in the virtual env, but doable
When wheel for python 3.11 will be released?

Thanks
L.

Il giorno ven 5 gen 2024 alle 15:09 Daniel Flehner Heen <
***@***.***> ha scritto:

**Comment by apetrynet** [comment]
Great! Sorry about the inconvenience. 
The next release should be out in not too long, but I'm afraid I don't have an exact date.

I'll close this ticket for now. Please reopen if you disagree.
