### ISSUE TITLE
Sample Python code throws an error

### ISSUE THREAD

**Issue by miguelmorin** [AcademySoftwareFoundation/OpenTimelineIO#1694]
### Incorrect Functionality and General Questions

The `README.md` shows sample usage in Python:

```
import opentimelineio as otio

timeline = otio.adapters.read_from_file("foo.aaf")
for clip in timeline.find_clips():
  print(clip.name, clip.duration())
```

when I run that, I get:

```
AttributeError: 'opentimelineio._otio.SerializableCollection' object has no attribute 'find_clips'
```

## To Reproduce

1. Operating System: macOS Big Sur
2. Python version 3.11.6
4. OpenTimelineIO release version 0.15.0
5. Compiler information:

```
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

## Expected Behavior

I expected the sample code to run without errors.

**Comment by reinecke** [comment]
Closing because the mismatch will disappear with the 0.16.0 release.
