### ISSUE TITLE
Build failing due to problem with actions/setup-python & Python 3.7

### ISSUE THREAD

**Issue by tomviner** [AcademySoftwareFoundation/OpenTimelineIO#1802]
# Required:
------------
- [x] I believe this isn't a duplicate topic  
- [x] This report is not related to an adapter  

## Select One:

- [x] Build problem  
- [ ] Incorrect Functionality or bug  
- [ ] New feature or functionality  

## Description
The _py_build_test (ubuntu-latest, 3.7)_ job has failed the last couple of times it ran. E.g. https://github.com/AcademySoftwareFoundation/OpenTimelineIO/actions/runs/11280378915/job/31373224050

The error message has been reported on the setup-python actions repo, by another project having the same error:
https://github.com/actions/setup-python/issues/962 

I can't see a recent change to Python 3.7 in the actions repo, so I'm not sure the cause. So hopefully, we can just await a fix and re-run the actions.

**Comment by jminor** [comment]
The error message says 3.7 x64 was not found, and links to this list of available versions which *does* include 3.7 x64 for linux. https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json

Maybe that list changed since the failure? I pressed the "Re-run jobs" button to see if it works now.

**Comment by jminor** [comment]
Run-running the jobs succeeded - yay!

However, from reading this https://github.com/actions/setup-python/issues/962 (thanks for the link @tomviner ) it seems that we will likely encounter this again as `ubuntu-latest` moves forward, and older versions of Python drop off. We can either set our runners to use older Ubuntu releases, or drop support for older Python releases (or run those separately). This overlaps with OTIO/ASWF policy for which VFX Platform versions to support: https://vfxplatform.com

@reinecke or @meshula can you remind me of how many years of VFX Platform we're supposed to support?

**Comment by meshula** [comment]
current year plus 3 reflects our current consensus. Python 3.7 has dropped off the support list by that measure. Note that 3.7 is incompatible with some platforms we support (eg, apple silicon support is in 3.9.1+).

**Comment by jminor** [comment]
The badge on our README shows 2020-2023, so we should update that. Is "current" the calendar year (2024) or the latest VFX (2025)? That difference puts VFX 2021 w/ Python 3.7 in or out of bounds.

**Comment by jminor** [comment]
Oh, never mind. I see that VFX 2025 is only in draft, so we should support 2024-2021.

**Comment by jminor** [comment]
Okay, I filed this: https://github.com/AcademySoftwareFoundation/OpenTimelineIO/issues/1804 to track the change we need to do. Since the build is working now, I'll close this issue. Thanks for flagging this @tomviner
