### ISSUE TITLE
Timecodes cause issue with RationalTime

### ISSUE THREAD

**Issue by alatdneg** [AcademySoftwareFoundation/OpenTimelineIO#336]
Hiya, I've been playing with timecodes and media references, it was going great until I hit problems with comparing Time/Ranges.

It was going fine until I tried the following.

>>> range_from_start_end_time(from_timecode("01:00:00:00",24.0), from_timecode("01:00:01:00",24.0)).contains(range_from_start_end_time(from_timecode("01:00:00:00",23.976), from_timecode("01:00:01:00",23.976)))
>>> False

I'm wondering how we're meant to deal with this, are using TimeRanges/Rational times as containers for timecodes, is it just a non starter, dues to their odd behavior.

In timecode land  23.976 == 24.0, in RationalTime etc, 23.976 != 24.0. 

cheers!

**Comment by jminor** [comment]
Support for timecode rates was improved in this PR: https://github.com/AcademySoftwareFoundation/OpenTimelineIO/pull/1477
