### ISSUE TITLE
AAF/XML Reader: Clip enabled/disabled/muted flag?

### ISSUE THREAD

**Issue by andrewmoore-nz** [AcademySoftwareFoundation/OpenTimelineIO#483]
There currently seems to be no "status" flag that comes with a clip object to convey its state on the timeline regarding whether it is active, has been disabled, muted, etc... 

I'm not sure how this is handled on the AAF side of things, but taking a quick look at the XML, there are the fields for each track and clip **<enabled></enabled>** that carry this information in a easily accessible place. Is there somewhere appropriate within the OTIO clip structure that this information could be stored? Having the enabled status of both clips and tracks is fairly important in trying to figure out what on the timeline actually needs to be considered. 

Have put together a quick test Premiere project to try the different combinations. Files here:

[ClipEnableMuteTesting_Examples_1904048.zip](https://github.com/PixarAnimationStudios/OpenTimelineIO/files/3052887/ClipEnableMuteTesting_Examples_1904048.zip)

**Comment by ssteinbach** [comment]
In the AAF adapter we turn muted clips into gaps and stuff the original objects into metadata so that we can round trip it, but we haven't taken a position on a "mute" attribute for OTIO.  Do Premiere and Media Composer handle 'muted' clips in the same way?

You can see what we did in AAF here: #335

**Comment by andrewmoore-nz** [comment]
Yeah, I soon realised that all of the GAP events I was seeing were actually the muted clips coming through in the AAF from Media Composer. I've got Media Composer on another machine here so am going to create a few more test files shortly. 

The Premiere AAF I put together yesterday with muted clips is not being treated the same way (i.e. they are not coming through as Gap objects) so I would likely say that they are not handled the same way in Media Composer and Premiere. The XML is also having all of its disabled/muted fields ignored and all clips are coming through as active Clip objects. 

Will let you know if I am able to get any more specific information after I've been able to put together some more test sequences from Media Composer.

**Comment by ssteinbach** [comment]
If you have two tracks, each with one clip, lets say "A" and "B", and "A" is "above" "B" such that if you flattened the tracks all you would see is "A", and then you mute "A", does the same thing happen in both packages?  Do they both become transparent?

**Comment by andrewmoore-nz** [comment]
Yes, that is correct. If you have the one video clip on top of another in both Premiere and Media Composer, you can select "Mute Clips" in MC, or select/uncheck "Enable" in Premiere, and the top clip becomes transparent, showing the clip underneath. 

Having just put together a test sequence in MC, I can confirm that "Muted" clips from a MC AAF come through in to OTIO as Gap objects, but "Disabled" clips from a Premiere AAF are coming through in to OTIO as Clip objects.  There is also the fact that video/audio tracks in MC and Premiere can be muted/disabled and this would need to be considered somewhere too. 

From my perspective, it seems like simply adding an "enabled" field to a track and clip object would be a fairly easy/tidy way to cover this, and be a lot easier to handle than having to extract the clip information from a gap object in order to work with it.

**Comment by ssteinbach** [comment]
Based on this I would define it on `core.Item`, I think.  So _not_ on `schema.Timeline` or `schema.SerializableCollection`.

More questions for the group:

- For `top_clip_at_time`, does that take muted/unmuted into account or are muted clips still functionally opaque?
- Should `each_clip()` and `each_item()` have flags that allow them to ignore and filter out muted clips?
- Should transitions be mutable and if so, what happens?  
- Is the generally policy that a disabled or 'muted' `Item` is treated as functionally identical to `Gap`?  So they still participate in `duration` computations but are not considered `opaque`?

**Comment by thecargocultnz** [comment]
> Updating from my previous comment, I think an enabled flag on `Clip`, `Effect`, and `Track` would encapsulate the known use cases.

In Premiere (and maybe others), nested sequences can also be "disabled", just like a clip.
So we need an ENABLED flag on the STACK object as well, right?

**Comment by jminor** [comment]
If we add this to the `Item` class, then it would be available on `Clip`, `Stack`, `Track`, etc. The only classes mentioned above that wouldn't cover are `Timeline` and `Effect` which do not inherit from `Item`.

**Comment by andrewmoore-nz** [comment]
@jminor @ssteinbach @reinecke Was any progress ever made on this concept? It seems that the use case for this is still very relevant.

**Comment by ssteinbach** [comment]
To my knowledge, no one has worked on this.  Looking over this issue now, I think my suggestion would be, if you wanted to take a pass at it, to build out a google doc or documentation file in the repo itself that describes how the muted functionality would work in the data model.  That could outline which checks to existing functionality need to be added such that muted clips are handled differently from normal clips.

**Comment by jminor** [comment]
FYI #1175 has landed now, so there is support for `enabled=False` on Items (Clip, etc.). Here is a PR that adds read support for this in the AAF adapter: #1212

**Comment by jminor** [comment]
This was addressed by https://github.com/AcademySoftwareFoundation/OpenTimelineIO/pull/1277
