### ISSUE TITLE
Marker: Add comment to schema

### ISSUE THREAD

**Issue by reinecke** [AcademySoftwareFoundation/OpenTimelineIO#744]
In addition to color and/or name, some NLE packages support a comment in their markers. The marker schema could add a top-level `comment` property to hold this data.

There are some format-specific differences.

FCP 7 XML seems to line up pretty nicely with this using the `comment` tag: https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/FinalCutPro_XML/Elements/Elements.html#//apple_ref/doc/uid/TP30001156-TPXREF106

AAF provides some interesting discussion points as it does not have a discrete name and comment field. Per @stefanschulze:
> there is not really a name in AAF for a marker, so it probably would work to use the name as the comment-content. But a marker comment in AAF could be large and is really different than what I’d understand to be a name. I think it would be better not to conflate these two notions.

**Comment by jminor** [comment]
It looks like Media Composer treats `name` and `comment` as two different things from the user's perspective.
![image](https://user-images.githubusercontent.com/169599/86185634-a82fb080-baeb-11ea-8282-064c33b4a632.png)

**Comment by jminor** [comment]
and the linked FCP 7 XML documents mention both `name` and `comment`:
```
marker
Description
    Encodes a named time or range of time in a clip or sequence.
Parents
    clip, clipitem, sequence
Subelements
    +*name, +in, +out,*marker, *comment, color
```

Do both of those show up in the user interface in Premiere or Resolve or other tools that support FCPXML?

**Comment by reinecke** [comment]
Here is the marker interface from Premiere Pro 2020:
![image](https://user-images.githubusercontent.com/1649087/86188895-e087bc80-baf4-11ea-9934-25ec4e6abbd8.png)

I tried various marker types, but they all seem to manifest the same in FCP 7 XML:

```xml
<marker>
    <comment>Comment on web marker</comment>
    <name>Web Marker</name>
    <in>797</in>
    <out>-1</out>
    <pproColor>4280578025</pproColor>
</marker>
```

**Comment by reinecke** [comment]
Here is the Marker Editing interface in Resolve 16:
![image](https://user-images.githubusercontent.com/1649087/86189641-feeeb780-baf6-11ea-8551-e62280e88ed1.png)

However, in FCP 7 XML and .edl formats it does not seem to export marker data.

**Comment by jminor** [comment]
So they all seem to support both `name` and `comment` (or "Notes" which seems synonymous) and some have extra keywords, type, and/or type-specific info.

I think adding `comment` to the Marker schema seems like a good choice since it could easily be handled by most of the adapters, and is likely part of some real world interchange workflows.

Does anyone want to advocate for `keywords` or `type` also? Those could be left as adapter-specific metadata on the Marker, since they don't have clear translation between most of these existing formats.

**Comment by apetrynet** [comment]
Hiero/NS has notes on markers as well. In these application the markers are actually Tags, so don't think keywords/type are needed, but wouldn't be a problem dealing with. Could actually be a useful way to store the tag type when I think of it.
