### ISSUE TITLE
CII Badge

### ISSUE THREAD

**Issue by ssteinbach** [AcademySoftwareFoundation/OpenTimelineIO#748]
We need to meet the conditions of the CII Badge:

https://github.com/coreinfrastructure/best-practices-badge/blob/master/doc/criteria.md

The first task is to break this list down into a concrete check list.

Checklist from best practices.coreinsfrastructure.org site:
https://bestpractices.coreinfrastructure.org/en/projects/2288

To-do Items:
- [x] Finish migration to Apache 2.0 License (floss_license, floss_license_osi)
- [x] OpenTimelineIO must be https (sites_https)
- [ ] Process for vulnerability reporting [OpenEXR](https://github.com/AcademySoftwareFoundation/openexr/blob/master/SECURITY.md) for reference (vulnerability_report_process, vulnerability_report_private, vulnerability_report_response)
- [ ] Break non-C++ and Python code into other repos (warnings)
- [ ] Talk to Linux Foundation rep about getting a developer up on secure development knowledge (know_secure_design)

**Comment by jminor** [comment]
I updated our entry on the CII system. We are currently at 61%

https://bestpractices.coreinfrastructure.org/en/projects/2288

**Comment by jminor** [comment]
I'm splitting this issue into separate issues for each actionable step to help us make progress here.
For example:
- https://github.com/AcademySoftwareFoundation/OpenTimelineIO/issues/1405
- https://github.com/AcademySoftwareFoundation/OpenTimelineIO/issues/1406
- https://github.com/AcademySoftwareFoundation/OpenTimelineIO/issues/1407
- https://github.com/AcademySoftwareFoundation/OpenTimelineIO/issues/1408
