### ISSUE TITLE
Transfer OTIO repo from Pixar to ASWF

### ISSUE THREAD

**Issue by jminor** [AcademySoftwareFoundation/OpenTimelineIO#814]
Part of our ASWF graduation process involves transferring the OpenTimelineIO GitHub repo from Pixar to the Academy Software Foundation.

This will happen after we have all the legal aspects in place.

Here are detailed instructions:
https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/transferring-a-repository

**Comment by apetrynet** [comment]
Not sure if this comment should go here, but could the move be a good occasion to move from master to main branch?

**Comment by ssteinbach** [comment]
Good question!  We have been tracking that on this card: https://github.com/PixarAnimationStudios/OpenTimelineIO/projects/8#card-46141519

which we should make into an issue.  The short answer is that we wanted to wait until GitHub provides tooling for making this transition.

**Comment by apetrynet** [comment]
Great! Since we need to swap remotes anyway it should be easy swap branch name in the same process.

**Comment by ssteinbach** [comment]
Users don't actually need to do anything for the master->main change.  Github has machinery that will redirect things done against master to main.

**Comment by jminor** [comment]
The OpenTimelineIO repo has been moved here: https://github.com/AcademySoftwareFoundation/OpenTimelineIO
